"""
Seed de equipamentos D&D 3.5 atualizado com dados da Tabela 7-5
Gerado automaticamente a partir da planilha Excel
"""

EQUIPAMENTOS_PADRAO = [
    ("Ataque desarmado", "Categoria: Armas simples; Dano: 1d3", "PHB p.120-126"),
    ("Manopla", "Categoria: Armas simples; Custo: 2 PO; Dano: 1d3", "PHB p.120-126"),
    ("Adaga", "Categoria: Armas simples; Custo: 2 PO; Dano: 1d4", "PHB p.120-126"),
    ("Adaga de soco", "Categoria: Armas simples; Custo: 2 PO; Dano: 1d4", "PHB p.120-126"),
    ("Foice curta", "Categoria: Armas simples; Custo: 6 PO; Dano: 1d6", "PHB p.120-126"),
    ("Maça leve", "Categoria: Armas simples; Custo: 5 PO; Dano: 1d6", "PHB p.120-126"),
    ("Manopla com cravos", "Categoria: Armas simples; Custo: 5 PO; Dano: 1d4", "PHB p.120-126"),
    ("Clava", "Categoria: Armas simples; Dano: 1d6", "PHB p.120-126"),
    ("Lança curta", "Categoria: Armas simples; Custo: 1 PO; Dano: 1d6", "PHB p.120-126"),
    ("Maça pesada", "Categoria: Armas simples; Custo: 12 PO; Dano: 1d8", "PHB p.120-126"),
]

EQUIPAMENTOS_DADOS = [
    {
        'nome': "Ataque desarmado",
        'categoria': "Armas simples",
        'subcategoria': None,
        'custo': None,
        'dano_pequeno': "1d2",
        'dano_medio': "1d3",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': None,
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Manopla",
        'categoria': "Armas simples",
        'subcategoria': None,
        'custo': "2 PO",
        'dano_pequeno': "1d2",
        'dano_medio': "1d3",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Adaga",
        'categoria': "Armas simples",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "2 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "19–20/×2",
        'alcance_incremento': "3 m",
        'peso': "0,5 kg",
        'tipo_dano': "Perfurante ou cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Adaga de soco",
        'categoria': "Armas simples",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "2 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Foice curta",
        'categoria': "Armas simples",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "6 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Maça leve",
        'categoria': "Armas simples",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "5 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "2 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Manopla com cravos",
        'categoria': "Armas simples",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "5 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Clava",
        'categoria': "Armas simples",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': None,
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "1,5 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Lança curta",
        'categoria': "Armas simples",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "1 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': "6 m",
        'peso': "1,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Maça pesada",
        'categoria': "Armas simples",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "12 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "4 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Maça-estrela",
        'categoria': "Armas simples",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "3 kg",
        'tipo_dano': "Concussão e perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Bordão⁵",
        'categoria': "Armas simples",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': None,
        'dano_pequeno': "1d4/1d4",
        'dano_medio': "1d6/1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "2 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Lança",
        'categoria': "Armas simples",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "2 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': "6 m",
        'peso': "3 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Lança longa⁴",
        'categoria': "Armas simples",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "5 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "4,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Azagaia",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': "9 m",
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Besta leve",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "35 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "19–20/×2",
        'alcance_incremento': "24 m",
        'peso': "2 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Virotes de besta (10)",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Besta pesada",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "50 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "19–20/×2",
        'alcance_incremento': "36 m",
        'peso': "4 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Virotes de besta (10)",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Dardo",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "5 PP",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': "6 m",
        'peso': "0,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Funda",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': None,
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': "15 m",
        'peso': "0 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Balas de funda (10)",
        'categoria': "Armas simples",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PP",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "2,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Armaduras com cravos",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "especial",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "especial",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Escudo pequeno",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "especial",
        'dano_pequeno': "1d2",
        'dano_medio': "1d3",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "especial",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Escudo pequeno com cravos",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "especial",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "especial",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Espada curta",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "10 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Kukri",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "18–20/×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machadinha",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "6 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machado de arremesso",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "1 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Martelo leve",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "1 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': "6 m",
        'peso': "1 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Picareta leve",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "4 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×4",
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Porrete",
        'categoria': "Armas comuns",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "1 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Cimitarra",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "15 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "18–20/×2",
        'alcance_incremento': None,
        'peso': "2 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Escudo grande",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "especial",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "especial",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Escudo grande com cravos",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "especial",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "especial",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Espada longa",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "15 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "2 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machado de batalha",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "10 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "3 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Mangual",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "2,5 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Martelo de guerra",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "12 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "2,5 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Picareta pesada",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×4",
        'alcance_incremento': None,
        'peso': "3 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Sabre",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "20 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "18–20/×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Tridente",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "15 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "2 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Alabarda",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "10 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "11 kg",
        'tipo_dano': "Perfurante ou cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Clava grande",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "5 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "4 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Espada larga",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "50 PO",
        'dano_pequeno': "1d10",
        'dano_medio': "2d6",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "4 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Falcione",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "75 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "2d4",
        'critico': "18–20/×2",
        'alcance_incremento': None,
        'peso': "4 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Foice longa",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "18 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "2d4",
        'critico': "×4",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Perfurante ou cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Glaive⁴",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "8 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Guisarme⁴",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "9 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "2d4",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "11 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Lança⁴",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "10 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machado grande",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "20 PO",
        'dano_pequeno': "1d10",
        'dano_medio': "1d12",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "11 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Mangual pesado",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "15 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Ranseur⁴",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "10 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "2d4",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "11 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Arco curto",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "30 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×3",
        'alcance_incremento': "18 m",
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Flechas (20)",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Arco curto composto",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "75 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×3",
        'alcance_incremento': "21 m",
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Flechas (20)",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Arco longo",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "75 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': "30 m",
        'peso': "1,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Flechas (20)",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Arco longo composto",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "100 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "×3",
        'alcance_incremento': "33 m",
        'peso': "1,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Flechas (20)",
        'categoria': "Armas comuns",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "1,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Kama",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "2 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Nunchaku",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "2 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Sai",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "1 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "0,5 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Siangham",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas leves – corpo a corpo",
        'custo': "3 PO",
        'dano_pequeno': "1d4",
        'dano_medio': "1d6",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Chicote⁴",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "1 PO",
        'dano_pequeno': "1d2",
        'dano_medio': "1d3",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "1 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Espada bastarda",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "35 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "3 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machado de guerra anão",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de uma mão – corpo a corpo",
        'custo': "30 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "4 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Corrente com cravos⁴",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "25 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "2d4",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Espada de duas lâminas⁵",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "100 PO",
        'dano_pequeno': "1d6/1d6",
        'dano_medio': "1d8/1d8",
        'critico': "19–20/×2",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Machado orc duplo⁵",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "60 PO",
        'dano_pequeno': "1d6/1d6",
        'dano_medio': "1d8/1d8",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "12,5 kg",
        'tipo_dano': "Cortante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Mangual atroz⁵",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "90 PO",
        'dano_pequeno': "1d6/1d6",
        'dano_medio': "1d8/1d8",
        'critico': "×2",
        'alcance_incremento': None,
        'peso': "10 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Martelo gnomo com gancho⁵",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "20 PO",
        'dano_pequeno': "1d6/1d4",
        'dano_medio': "1d8/1d6",
        'critico': "×3/×4",
        'alcance_incremento': None,
        'peso': "3 kg",
        'tipo_dano': "Concussão e perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Urgrosh anão⁵",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de duas mãos – corpo a corpo",
        'custo': "50 PO",
        'dano_pequeno': "1d6/1d4",
        'dano_medio': "1d8/1d6",
        'critico': "×3",
        'alcance_incremento': None,
        'peso': "11 kg",
        'tipo_dano': "Cortante ou perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Besta leve de repetição",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "250 PO",
        'dano_pequeno': "1d6",
        'dano_medio': "1d8",
        'critico': "19–20/×2",
        'alcance_incremento': "24 m",
        'peso': "3 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Virotes de besta (5)",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Besta pesada de repetição",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "400 PO",
        'dano_pequeno': "1d8",
        'dano_medio': "1d10",
        'critico': "19–20/×2",
        'alcance_incremento': "36 m",
        'peso': "11 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Virotes de besta (5)",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Besta de mão",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "100 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "19–20/×2",
        'alcance_incremento': "9 m",
        'peso': "1 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Virotes de besta (10)",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': "0,5 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Boleadeira",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "5 PO",
        'dano_pequeno': "1d3",
        'dano_medio': "1d4",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "1 kg",
        'tipo_dano': "Concussão",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Rede",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "20 PO",
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': "3 m",
        'peso': "3 kg",
        'tipo_dano': None,
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
    {
        'nome': "Shuriken (5)",
        'categoria': "Armas exóticas",
        'subcategoria': "Armas de ataque à distância",
        'custo': "1 PO",
        'dano_pequeno': "1",
        'dano_medio': "1d2",
        'critico': "×2",
        'alcance_incremento': "3 m",
        'peso': "0,25 kg",
        'tipo_dano': "Perfurante",
        'pagina_referencia': "PHB p.120-126",
        'ativo': True
    },
]

def seed_equipamentos(db):
    """
    Popula a tabela de equipamentos com dados da Tabela 7-5.
    """
    from app.models.equipamento import Equipamento
    from datetime import datetime, timezone

    # Verificar se já existem equipamentos
    count = db.query(Equipamento).count()
    if count > 0:
        print(f"✅ Equipamentos já existem ({count}). Pulando seed.")
        return

    print("📦 Iniciando seed de equipamentos da Tabela 7-5...")

    for equipamento_data in EQUIPAMENTOS_DADOS:
        equipamento = Equipamento(
            nome=equipamento_data['nome'],
            categoria=equipamento_data.get('categoria'),
            subcategoria=equipamento_data.get('subcategoria'),
            custo=equipamento_data.get('custo'),
            dano_pequeno=equipamento_data.get('dano_pequeno'),
            dano_medio=equipamento_data.get('dano_medio'),
            critico=equipamento_data.get('critico'),
            alcance_incremento=equipamento_data.get('alcance_incremento'),
            peso=equipamento_data.get('peso'),
            tipo_dano=equipamento_data.get('tipo_dano'),
            pagina_referencia=equipamento_data.get('pagina_referencia'),
            ativo=equipamento_data.get('ativo', True),
            criado_em=datetime.now(timezone.utc)
        )
        db.add(equipamento)

    db.commit()
    print(f"✅ {len(EQUIPAMENTOS_DADOS)} equipamentos inseridos com sucesso!")
