"""
Seed de equipamentos D&D 3.5 — Tabela 7-5 (armas).
Gerado automaticamente por processar_equipamentos_excel.py a partir da planilha Excel.
Não editar EQUIPAMENTOS_DADOS à mão; regenere o arquivo com o script.
"""

from datetime import datetime, timezone

EQUIPAMENTOS_DADOS = [
    {
        'nome': 'Ataque desarmado',
        'categoria': 'Armas simples',
        'subcategoria': None,
        'custo': None,
        'dano_pequeno': '1d2',
        'dano_medio': '1d3',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': None,
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Manopla',
        'categoria': 'Armas simples',
        'subcategoria': None,
        'custo': '2 PO',
        'dano_pequeno': '1d2',
        'dano_medio': '1d3',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Adaga',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '2 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '19–20/×2',
        'alcance_incremento': '3 m',
        'peso': '0,5 kg',
        'tipo_dano': 'Perfurante ou cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Adaga de soco',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '2 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Foice curta',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '6 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Maça leve',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '5 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '2 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Manopla com cravos',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '5 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Clava',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': None,
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '1,5 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Lança curta',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '1 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': '6 m',
        'peso': '1,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Maça pesada',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '12 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '4 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Maça-estrela',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '3 kg',
        'tipo_dano': 'Concussão e perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Bordão⁵',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': None,
        'dano_pequeno': '1d4/1d4',
        'dano_medio': '1d6/1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '2 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Lança',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '2 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': '6 m',
        'peso': '3 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Lança longa⁴',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '5 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '4,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Azagaia',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': '9 m',
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Besta leve',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '35 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '19–20/×2',
        'alcance_incremento': '24 m',
        'peso': '2 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Virotes de besta (10)',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Besta pesada',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '50 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '19–20/×2',
        'alcance_incremento': '36 m',
        'peso': '4 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Virotes de besta (10)',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Dardo',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '5 PP',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': '6 m',
        'peso': '0,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Funda',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': None,
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': '15 m',
        'peso': '0 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Balas de funda (10)',
        'categoria': 'Armas simples',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PP',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '2,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Armaduras com cravos',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': 'especial',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': 'especial',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Escudo pequeno',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': 'especial',
        'dano_pequeno': '1d2',
        'dano_medio': '1d3',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': 'especial',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Escudo pequeno com cravos',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': 'especial',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': 'especial',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Espada curta',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '10 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Kukri',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '18–20/×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machadinha',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '6 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machado de arremesso',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '1 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Martelo leve',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '1 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': '6 m',
        'peso': '1 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Picareta leve',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '4 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×4',
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Porrete',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '1 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Cimitarra',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '15 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '18–20/×2',
        'alcance_incremento': None,
        'peso': '2 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Escudo grande',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': 'especial',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': 'especial',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Escudo grande com cravos',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': 'especial',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': 'especial',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Espada longa',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '15 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '2 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machado de batalha',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '10 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '3 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Mangual',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '2,5 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Martelo de guerra',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '12 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '2,5 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Picareta pesada',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×4',
        'alcance_incremento': None,
        'peso': '3 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Sabre',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '20 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '18–20/×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Tridente',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '15 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '2 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Alabarda',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '10 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '11 kg',
        'tipo_dano': 'Perfurante ou cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Clava grande',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '5 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '4 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Espada larga',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '50 PO',
        'dano_pequeno': '1d10',
        'dano_medio': '2d6',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '4 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Falcione',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '75 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '2d4',
        'critico': '18–20/×2',
        'alcance_incremento': None,
        'peso': '4 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Foice longa',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '18 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '2d4',
        'critico': '×4',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Perfurante ou cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Glaive⁴',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '8 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Guisarme⁴',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '9 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '2d4',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '11 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Lança⁴',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '10 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machado grande',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '20 PO',
        'dano_pequeno': '1d10',
        'dano_medio': '1d12',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '11 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Mangual pesado',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '15 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Ranseur⁴',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '10 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '2d4',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '11 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Arco curto',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '30 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×3',
        'alcance_incremento': '18 m',
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Flechas (20)',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Arco curto composto',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '75 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×3',
        'alcance_incremento': '21 m',
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Flechas (20)',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Arco longo',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '75 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': '30 m',
        'peso': '1,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Flechas (20)',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Arco longo composto',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '100 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '×3',
        'alcance_incremento': '33 m',
        'peso': '1,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Flechas (20)',
        'categoria': 'Armas comuns',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '1,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Kama',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '2 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Nunchaku',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '2 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Sai',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '1 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '0,5 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Siangham',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas leves – corpo a corpo',
        'custo': '3 PO',
        'dano_pequeno': '1d4',
        'dano_medio': '1d6',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Chicote⁴',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '1 PO',
        'dano_pequeno': '1d2',
        'dano_medio': '1d3',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '1 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Espada bastarda',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '35 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '3 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machado de guerra anão',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de uma mão – corpo a corpo',
        'custo': '30 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '4 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Corrente com cravos⁴',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '25 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '2d4',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Espada de duas lâminas⁵',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '100 PO',
        'dano_pequeno': '1d6/1d6',
        'dano_medio': '1d8/1d8',
        'critico': '19–20/×2',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Machado orc duplo⁵',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '60 PO',
        'dano_pequeno': '1d6/1d6',
        'dano_medio': '1d8/1d8',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '12,5 kg',
        'tipo_dano': 'Cortante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Mangual atroz⁵',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '90 PO',
        'dano_pequeno': '1d6/1d6',
        'dano_medio': '1d8/1d8',
        'critico': '×2',
        'alcance_incremento': None,
        'peso': '10 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Martelo gnomo com gancho⁵',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '20 PO',
        'dano_pequeno': '1d6/1d4',
        'dano_medio': '1d8/1d6',
        'critico': '×3/×4',
        'alcance_incremento': None,
        'peso': '3 kg',
        'tipo_dano': 'Concussão e perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Urgrosh anão⁵',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de duas mãos – corpo a corpo',
        'custo': '50 PO',
        'dano_pequeno': '1d6/1d4',
        'dano_medio': '1d8/1d6',
        'critico': '×3',
        'alcance_incremento': None,
        'peso': '11 kg',
        'tipo_dano': 'Cortante ou perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Besta leve de repetição',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '250 PO',
        'dano_pequeno': '1d6',
        'dano_medio': '1d8',
        'critico': '19–20/×2',
        'alcance_incremento': '24 m',
        'peso': '3 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Virotes de besta (5)',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Besta pesada de repetição',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '400 PO',
        'dano_pequeno': '1d8',
        'dano_medio': '1d10',
        'critico': '19–20/×2',
        'alcance_incremento': '36 m',
        'peso': '11 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Virotes de besta (5)',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Besta de mão',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '100 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '19–20/×2',
        'alcance_incremento': '9 m',
        'peso': '1 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Virotes de besta (10)',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': None,
        'peso': '0,5 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Boleadeira',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '5 PO',
        'dano_pequeno': '1d3',
        'dano_medio': '1d4',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '1 kg',
        'tipo_dano': 'Concussão',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Rede',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '20 PO',
        'dano_pequeno': None,
        'dano_medio': None,
        'critico': None,
        'alcance_incremento': '3 m',
        'peso': '3 kg',
        'tipo_dano': None,
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
    {
        'nome': 'Shuriken (5)',
        'categoria': 'Armas exóticas',
        'subcategoria': 'Armas de ataque à distância',
        'custo': '1 PO',
        'dano_pequeno': '1',
        'dano_medio': '1d2',
        'critico': '×2',
        'alcance_incremento': '3 m',
        'peso': '0,25 kg',
        'tipo_dano': 'Perfurante',
        'pagina_referencia': 'PHB p.120-126',
        'ativo': True,
    },
]


def _montar_descricao(eq: dict) -> str | None:
    """Resumo curto para o campo legado descricao (UI / listagens)."""
    partes = []
    if eq.get("categoria"):
        partes.append(eq["categoria"])
    if eq.get("subcategoria"):
        partes.append(eq["subcategoria"])
    if eq.get("custo"):
        partes.append(f"Custo: {eq['custo']}")
    if eq.get("dano_medio"):
        partes.append(f"Dano (M): {eq['dano_medio']}")
    if eq.get("tipo_dano"):
        partes.append(eq["tipo_dano"])
    return "; ".join(partes) if partes else None


def seed_equipamentos(db) -> None:
    """
    Sincroniza o catálogo com a Tabela 7-5.

    - Remove entradas legadas (sem categoria) não usadas em equipamentos_jogador.
    - Para cada item da planilha: insere ou atualiza por nome (entre ativos).
    """
    from app.models.equipamento import Equipamento, EquipamentoJogador

    usados = {
        row[0]
        for row in db.query(EquipamentoJogador.equipamento_id).distinct().all()
        if row[0] is not None
    }

    legado = (
        db.query(Equipamento)
        .filter(Equipamento.deleted_at.is_(None), Equipamento.categoria.is_(None))
        .all()
    )
    removidos = 0
    for eq in legado:
        if eq.id not in usados:
            db.delete(eq)
            removidos += 1
    if removidos:
        db.flush()
        print(f"🧹 Removidos {removidos} equipamentos legados (sem categoria, não referenciados).")

    inseridos = 0
    atualizados = 0

    for data in EQUIPAMENTOS_DADOS:
        nome = data["nome"]
        descricao = _montar_descricao(data)
        row = (
            db.query(Equipamento)
            .filter(Equipamento.nome == nome, Equipamento.deleted_at.is_(None))
            .first()
        )
        campos = {
            "descricao": descricao,
            "categoria": data.get("categoria"),
            "subcategoria": data.get("subcategoria"),
            "custo": data.get("custo"),
            "dano_pequeno": data.get("dano_pequeno"),
            "dano_medio": data.get("dano_medio"),
            "critico": data.get("critico"),
            "alcance_incremento": data.get("alcance_incremento"),
            "peso": data.get("peso"),
            "tipo_dano": data.get("tipo_dano"),
            "pagina_referencia": data.get("pagina_referencia"),
            "ativo": data.get("ativo", True),
        }
        if row:
            for k, v in campos.items():
                setattr(row, k, v)
            atualizados += 1
        else:
            db.add(
                Equipamento(
                    nome=nome,
                    **campos,
                    criado_em=datetime.now(timezone.utc),
                )
            )
            inseridos += 1

    db.commit()
    try:
        from app.core.config import settings
        from app.core.catalog_cache import catalog_cache

        if settings.CACHE_ENABLED:
            catalog_cache.invalidate_prefix("equipamentos:")
    except Exception:
        pass
    print(
        f"✅ Catálogo Tabela 7-5 sincronizado: +{inseridos} inseridos, "
        f"{atualizados} atualizados (total planilha: {len(EQUIPAMENTOS_DADOS)})."
    )
