"""
Seed de armaduras e itens de protecao D&D 3.5 (Tabela 7-6).
Gerado automaticamente a partir da planilha Excel.
"""

from datetime import datetime, timezone

from app.models.armadura_protecao import ArmaduraProtecao


ARMADURAS_PROTECAO_DADOS = [
    {
        'nome': 'Acolchoada',
        'tipo': 'Armadura',
        'bonus_ca': 1,
        'des_max': '+8',
        'penalidade': 0,
        'falha_arcana': '5%',
        'deslocamento': '9m: 9 m | 6m: 6 m',
        'peso': 5.0,
        'propriedades_especiais': 'Custo: 5 PO',
        'ativo': True,
    },
    {
        'nome': 'Couro',
        'tipo': 'Armadura',
        'bonus_ca': 2,
        'des_max': '+6',
        'penalidade': 0,
        'falha_arcana': '10%',
        'deslocamento': '9m: 9 m | 6m: 6 m',
        'peso': 7.5,
        'propriedades_especiais': 'Custo: 10 PO',
        'ativo': True,
    },
    {
        'nome': 'Couro batido',
        'tipo': 'Armadura',
        'bonus_ca': 3,
        'des_max': '+5',
        'penalidade': -1,
        'falha_arcana': '15%',
        'deslocamento': '9m: 9 m | 6m: 6 m',
        'peso': 10.0,
        'propriedades_especiais': 'Custo: 25 PO',
        'ativo': True,
    },
    {
        'nome': 'Camisao de Cota de Malha',
        'tipo': 'Armadura',
        'bonus_ca': 4,
        'des_max': '+4',
        'penalidade': -2,
        'falha_arcana': '20%',
        'deslocamento': '9m: 9 m | 6m: 6 m',
        'peso': 12.5,
        'propriedades_especiais': 'Custo: 100 PO',
        'ativo': True,
    },
    {
        'nome': 'Gibao de Peles',
        'tipo': 'Armadura',
        'bonus_ca': 3,
        'des_max': '+4',
        'penalidade': -3,
        'falha_arcana': '20%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 12.5,
        'propriedades_especiais': 'Custo: 15 PO',
        'ativo': True,
    },
    {
        'nome': 'Brunea',
        'tipo': 'Armadura',
        'bonus_ca': 4,
        'des_max': '+3',
        'penalidade': -4,
        'falha_arcana': '25%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 15.0,
        'propriedades_especiais': 'Custo: 50 PO',
        'ativo': True,
    },
    {
        'nome': 'Cota de Malha',
        'tipo': 'Armadura',
        'bonus_ca': 5,
        'des_max': '+2',
        'penalidade': -5,
        'falha_arcana': '30%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 20.0,
        'propriedades_especiais': 'Custo: 150 PO',
        'ativo': True,
    },
    {
        'nome': 'Peitoral de Aco',
        'tipo': 'Armadura',
        'bonus_ca': 5,
        'des_max': '+3',
        'penalidade': -4,
        'falha_arcana': '25%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 15.0,
        'propriedades_especiais': 'Custo: 200 PO',
        'ativo': True,
    },
    {
        'nome': 'Cota de Talas',
        'tipo': 'Armadura',
        'bonus_ca': 6,
        'des_max': '+0',
        'penalidade': -7,
        'falha_arcana': '40%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 22.5,
        'propriedades_especiais': 'Custo: 20 PO',
        'ativo': True,
    },
    {
        'nome': 'Loriga Segmentada',
        'tipo': 'Armadura',
        'bonus_ca': 6,
        'des_max': '+1',
        'penalidade': -6,
        'falha_arcana': '35%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 17.5,
        'propriedades_especiais': 'Custo: 250 PO',
        'ativo': True,
    },
    {
        'nome': 'Meia Armadura',
        'tipo': 'Armadura',
        'bonus_ca': 7,
        'des_max': '+0',
        'penalidade': -7,
        'falha_arcana': '40%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 25.0,
        'propriedades_especiais': 'Custo: 600 PO',
        'ativo': True,
    },
    {
        'nome': 'Armadura de Batalha',
        'tipo': 'Armadura',
        'bonus_ca': 8,
        'des_max': '+1',
        'penalidade': -6,
        'falha_arcana': '35%',
        'deslocamento': '9m: 6 m | 6m: 4,5 m',
        'peso': 25.0,
        'propriedades_especiais': 'Custo: 1.500 PO',
        'ativo': True,
    },
    {
        'nome': 'Broquel',
        'tipo': 'Escudo',
        'bonus_ca': 1,
        'des_max': None,
        'penalidade': -1,
        'falha_arcana': '5%',
        'deslocamento': None,
        'peso': 2.5,
        'propriedades_especiais': 'Custo: 15 PO',
        'ativo': True,
    },
    {
        'nome': 'Escudo Pequeno de Madeira',
        'tipo': 'Escudo',
        'bonus_ca': 1,
        'des_max': None,
        'penalidade': -1,
        'falha_arcana': '5%',
        'deslocamento': None,
        'peso': 2.5,
        'propriedades_especiais': 'Custo: 3 PO',
        'ativo': True,
    },
    {
        'nome': 'Escudo Pequeno de Metal',
        'tipo': 'Escudo',
        'bonus_ca': 1,
        'des_max': None,
        'penalidade': -1,
        'falha_arcana': '5%',
        'deslocamento': None,
        'peso': 3.0,
        'propriedades_especiais': 'Custo: 9 PO',
        'ativo': True,
    },
    {
        'nome': 'Escudo Grande de Madeira',
        'tipo': 'Escudo',
        'bonus_ca': 2,
        'des_max': None,
        'penalidade': -2,
        'falha_arcana': '15%',
        'deslocamento': None,
        'peso': 5.0,
        'propriedades_especiais': 'Custo: 7 PO',
        'ativo': True,
    },
    {
        'nome': 'Escudo Grande de Metal',
        'tipo': 'Escudo',
        'bonus_ca': 2,
        'des_max': None,
        'penalidade': -2,
        'falha_arcana': '15%',
        'deslocamento': None,
        'peso': 7.5,
        'propriedades_especiais': 'Custo: 20 PO',
        'ativo': True,
    },
    {
        'nome': 'Escudo de Corpo',
        'tipo': 'Escudo',
        'bonus_ca': 4,
        'des_max': '+2',
        'penalidade': -10,
        'falha_arcana': '50%',
        'deslocamento': None,
        'peso': 22.5,
        'propriedades_especiais': 'Custo: 30 PO',
        'ativo': True,
    },
    {
        'nome': 'Cravos para Armadura',
        'tipo': 'Acessorio',
        'bonus_ca': 0,
        'des_max': None,
        'penalidade': 0,
        'falha_arcana': None,
        'deslocamento': None,
        'peso': 5.0,
        'propriedades_especiais': 'Custo: +50 PO | Item acessorio da tabela de armaduras e escudos.',
        'ativo': True,
    },
    {
        'nome': 'Manopla de Seguranca',
        'tipo': 'Acessorio',
        'bonus_ca': 0,
        'des_max': None,
        'penalidade': 0,
        'falha_arcana': None,
        'deslocamento': None,
        'peso': 2.5,
        'propriedades_especiais': 'Custo: 8 PO | Penalidade especial (consultar descricao do item). | Item acessorio da tabela de armaduras e escudos.',
        'ativo': True,
    },
    {
        'nome': 'Cravos para Escudos',
        'tipo': 'Acessorio',
        'bonus_ca': 0,
        'des_max': None,
        'penalidade': 0,
        'falha_arcana': None,
        'deslocamento': None,
        'peso': 2.5,
        'propriedades_especiais': 'Custo: +10 PO | Item acessorio da tabela de armaduras e escudos.',
        'ativo': True,
    },
]


def seed_armaduras_protecao(db):
    """
    Popula o catalogo de armaduras/itens de protecao da Tabela 7-6.
    """
    count = db.query(ArmaduraProtecao).count()
    if count > 0:
        print(f"✅ Armaduras/Protecao ja existem ({count}). Pulando seed.")
        return

    print("📦 Iniciando seed de armaduras/protecao da Tabela 7-6...")
    for item_data in ARMADURAS_PROTECAO_DADOS:
        item = ArmaduraProtecao(
            nome=item_data["nome"],
            tipo=item_data["tipo"],
            bonus_ca=item_data["bonus_ca"],
            des_max=item_data.get("des_max"),
            penalidade=item_data["penalidade"],
            falha_arcana=item_data.get("falha_arcana"),
            deslocamento=item_data.get("deslocamento"),
            peso=item_data.get("peso"),
            propriedades_especiais=item_data.get("propriedades_especiais"),
            ativo=item_data.get("ativo", True),
            criado_em=datetime.now(timezone.utc),
        )
        db.add(item)

    db.commit()
    print(f"✅ {len(ARMADURAS_PROTECAO_DADOS)} itens inseridos com sucesso!")
