"""
Catálogo de espécies de companheiro animal (nível inicial) — D&D 3.5 PHB.
Estatísticas base simplificadas (SRD); ajustes finos podem evoluir em seed dedicado.
"""

from __future__ import annotations

from typing import Any, Dict, List

# forca, destreza, constituicao, inteligencia, sabedoria, carisma
_ESPECIES: List[Dict[str, Any]] = [
    {
        "slug": "lobo",
        "nome": "Lobo",
        "categoria": "terrestre",
        "hd_base": 2,
        "armadura_natural_base": 2,
        "deslocamento": "12 m",
        "atributos_base": {
            "forca": 13,
            "destreza": 15,
            "constituicao": 15,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Mordida 1d6+mod FOR",
    },
    {
        "slug": "cao",
        "nome": "Cão",
        "categoria": "terrestre",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "12 m",
        "atributos_base": {
            "forca": 13,
            "destreza": 17,
            "constituicao": 15,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Mordida 1d4+mod FOR",
    },
    {
        "slug": "cao_montaria",
        "nome": "Cão de Montaria",
        "categoria": "terrestre",
        "hd_base": 2,
        "armadura_natural_base": 1,
        "deslocamento": "12 m",
        "atributos_base": {
            "forca": 15,
            "destreza": 15,
            "constituicao": 17,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Mordida 1d6+mod FOR",
    },
    {
        "slug": "texugo",
        "nome": "Texugo",
        "categoria": "terrestre",
        "hd_base": 1,
        "armadura_natural_base": 2,
        "deslocamento": "9 m",
        "atributos_base": {
            "forca": 8,
            "destreza": 17,
            "constituicao": 15,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Mordida 1d4+mod FOR",
    },
    {
        "slug": "camelo",
        "nome": "Camelo",
        "categoria": "terrestre",
        "hd_base": 3,
        "armadura_natural_base": 1,
        "deslocamento": "15 m",
        "atributos_base": {
            "forca": 18,
            "destreza": 13,
            "constituicao": 17,
            "inteligencia": 2,
            "sabedoria": 11,
            "carisma": 4,
        },
        "ataque_padrao": "Mordida 1d4+mod FOR",
    },
    {
        "slug": "rato_gigante",
        "nome": "Rato Gigante",
        "categoria": "terrestre",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "12 m",
        "atributos_base": {
            "forca": 10,
            "destreza": 15,
            "constituicao": 12,
            "inteligencia": 2,
            "sabedoria": 10,
            "carisma": 4,
        },
        "ataque_padrao": "Mordida 1d4+mod FOR",
    },
    {
        "slug": "cavalo_leve",
        "nome": "Cavalo (leve)",
        "categoria": "terrestre",
        "hd_base": 3,
        "armadura_natural_base": 1,
        "deslocamento": "18 m",
        "atributos_base": {
            "forca": 16,
            "destreza": 13,
            "constituicao": 17,
            "inteligencia": 2,
            "sabedoria": 13,
            "carisma": 6,
        },
        "ataque_padrao": "Cascos 1d4+mod FOR",
    },
    {
        "slug": "cavalo_pesado",
        "nome": "Cavalo (pesado)",
        "categoria": "terrestre",
        "hd_base": 3,
        "armadura_natural_base": 1,
        "deslocamento": "15 m",
        "atributos_base": {
            "forca": 18,
            "destreza": 13,
            "constituicao": 19,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Cascos 1d6+mod FOR",
    },
    {
        "slug": "poni",
        "nome": "Pônei",
        "categoria": "terrestre",
        "hd_base": 2,
        "armadura_natural_base": 1,
        "deslocamento": "12 m",
        "atributos_base": {
            "forca": 14,
            "destreza": 13,
            "constituicao": 15,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Cascos 1d3+mod FOR",
    },
    {
        "slug": "aguia",
        "nome": "Águia",
        "categoria": "aereo",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "3 m, voo 18 m",
        "atributos_base": {
            "forca": 10,
            "destreza": 15,
            "constituicao": 12,
            "inteligencia": 2,
            "sabedoria": 14,
            "carisma": 6,
        },
        "ataque_padrao": "Garras 1d4+mod FOR",
    },
    {
        "slug": "falcao",
        "nome": "Falcão",
        "categoria": "aereo",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "3 m, voo 18 m",
        "atributos_base": {
            "forca": 10,
            "destreza": 15,
            "constituicao": 12,
            "inteligencia": 2,
            "sabedoria": 14,
            "carisma": 6,
        },
        "ataque_padrao": "Garras 1d4+mod FOR",
    },
    {
        "slug": "coruja",
        "nome": "Coruja",
        "categoria": "aereo",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "3 m, voo 12 m",
        "atributos_base": {
            "forca": 10,
            "destreza": 15,
            "constituicao": 12,
            "inteligencia": 2,
            "sabedoria": 14,
            "carisma": 6,
        },
        "ataque_padrao": "Garras 1d4+mod FOR",
    },
    {
        "slug": "serpente_pequena",
        "nome": "Serpente Pequena",
        "categoria": "reptil",
        "hd_base": 1,
        "armadura_natural_base": 0,
        "deslocamento": "6 m",
        "atributos_base": {
            "forca": 10,
            "destreza": 17,
            "constituicao": 13,
            "inteligencia": 1,
            "sabedoria": 12,
            "carisma": 2,
        },
        "ataque_padrao": "Mordida 1d2+veneno",
    },
    {
        "slug": "serpente_media",
        "nome": "Serpente Média",
        "categoria": "reptil",
        "hd_base": 2,
        "armadura_natural_base": 0,
        "deslocamento": "6 m",
        "atributos_base": {
            "forca": 11,
            "destreza": 17,
            "constituicao": 13,
            "inteligencia": 1,
            "sabedoria": 12,
            "carisma": 2,
        },
        "ataque_padrao": "Mordida 1d4+veneno",
    },
    {
        "slug": "golfinho",
        "nome": "Golfinho",
        "categoria": "aquatico",
        "hd_base": 2,
        "armadura_natural_base": 0,
        "deslocamento": "Natação 24 m",
        "atributos_base": {
            "forca": 12,
            "destreza": 15,
            "constituicao": 13,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 6,
        },
        "ataque_padrao": "Cauda 1d4+mod FOR",
    },
    {
        "slug": "tubarão_medio",
        "nome": "Tubarão Médio",
        "categoria": "aquatico",
        "hd_base": 7,
        "armadura_natural_base": 2,
        "deslocamento": "Natação 18 m",
        "atributos_base": {
            "forca": 17,
            "destreza": 15,
            "constituicao": 15,
            "inteligencia": 1,
            "sabedoria": 12,
            "carisma": 4,
        },
        "ataque_padrao": "Mordida 1d6+mod FOR",
    },
    {
        "slug": "lula",
        "nome": "Lula",
        "categoria": "aquatico",
        "hd_base": 2,
        "armadura_natural_base": 0,
        "deslocamento": "Natação 18 m",
        "atributos_base": {
            "forca": 12,
            "destreza": 15,
            "constituicao": 11,
            "inteligencia": 2,
            "sabedoria": 12,
            "carisma": 4,
        },
        "ataque_padrao": "Tentáculos 1d4+mod FOR",
    },
]

_POR_SLUG = {e["slug"]: e for e in _ESPECIES}


def listar_especies() -> List[Dict[str, Any]]:
    return list(_ESPECIES)


def especie_por_slug(slug: str) -> Dict[str, Any] | None:
    return _POR_SLUG.get(str(slug or "").strip())
