"""add_new_spell_columns

Revision ID: 630072bd328c
Revises: 002_add_pagina_referencia
Create Date: 2026-03-20 17:15:34.861007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630072bd328c'
down_revision: Union[str, None] = '002_add_pagina_referencia'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combatente_condicoes', 'duracao_turnos',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('combatentes', 'pagina_referencia',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('magias', 'alcance',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('magias_preparadas', 'usada',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('magias_preparadas', 'usada',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               existing_nullable=False)
    op.alter_column('magias', 'alcance',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('combatentes', 'pagina_referencia',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("('')"),
               existing_nullable=True)
    op.alter_column('combatente_condicoes', 'duracao_turnos',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'-1'"),
               existing_nullable=False)
    # ### end Alembic commands ###
